imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: "%kernel.debug%"
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trust_proxy_headers: false # Deprecated in 2.0; will be removed in 2.3 (used trusted_proxies instead)
    trusted_proxies: ~
    session:         ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug: %kernel.debug%
    use_controller: false
    filters:
        cssrewrite: ~
        less:
           node: "%node%"
           node_paths: "%node_paths%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        path:     "%kernel.root_dir%/%database_name%.sqlite"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

ihqs_contact:
    contact:
        form:
            type:               ihqs_contact_contact
            handler:            ihqs_contact.contact.form.handler.default
            name:               ihqs_contact_contact_form
            validation_groups:  [Contact]
    form: ~                                 
    model: ~                                
    connectors:                             
        email:                              
            recipients: "%contact_recipient%"
        database:                           
            db_driver: orm                  
        file: ~                             