parameters:
    database_driver:   pdo_sqlite
    database_name:     data
    database_user:     root
    database_password: root

    mailer_transport:  smtp
    mailer_host:       127.0.0.1
    mailer_user:       ~
    mailer_password:   ~

    locale:            de
    secret:            8bc3c5c0f42c756d0101e1aa3413a74f
